apiVersion: v1
kind: Service
metadata:
  name: bridge
spec:
  clusterIP: None
  ports:
    - port: 11311
      protocol: TCP
      name: master
    - port: 5672
      protocol: TCP
      name: broker
  selector:
    name: bridge
  type: ClusterIP
