apiVersion: v1
kind: Pod
metadata:
  name: rrbridge
  labels:
    name: rrbridge
spec:
  containers:
   -  name: bridge
      image: localhost:5000/tof/rr_bridge
      imagePullPolicy: Always
      env:
        - name: ROS_HOSTNAME
          value: rrbridge
        - name: ROS_MASTER_URI
          value: http://master:11311
        - name: CLOUD_BROKER_HOST
          value: ros-broker
