apiVersion: v1
kind: Pod
metadata:
  name: amcl
  labels:
    name: amcl
spec:
  containers:
   -  name: amcl
      image: loeh/ros_amcl_node:latest
      imagePullPolicy: Always
      env:
        - name: ROS_HOSTNAME
          value: amcl
        - name: ROS_MASTER_URI
          value: http://master:11311
      args:
        - roslaunch
        - icclab_turtlebot
        - icclab.launch
        - map_file:=/home/turtlebot/catkin_ws/src/icclab_turtlebot/icclab_latest_map.yaml
