apiVersion: v1
kind: Pod
metadata:
  name: posepublisher
  labels:
    name: posepublisher
spec:
  containers:
    - env:
        - name: ROS_HOSTNAME
          value: posepublisher
        - name: ROS_MASTER_URI
          value: http://master:11311
      name: rosbridge
      image: loeh/ros_pose_publisher_node:latest
      ports:
        - containerPort: 11311
          name: posepublisher
